{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "b69ba405",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Figure(1000x500)\n",
      "Performing stepwise search to minimize aic\n",
      " ARIMA(2,1,2)(1,1,1)[12]             : AIC=526.837, Time=3.33 sec\n",
      " ARIMA(0,1,0)(0,1,0)[12]             : AIC=659.245, Time=0.17 sec\n",
      " ARIMA(1,1,0)(1,1,0)[12]             : AIC=560.558, Time=0.17 sec\n",
      " ARIMA(0,1,1)(0,1,1)[12]             : AIC=529.539, Time=0.60 sec\n",
      " ARIMA(2,1,2)(0,1,1)[12]             : AIC=525.356, Time=2.49 sec\n",
      " ARIMA(2,1,2)(0,1,0)[12]             : AIC=551.838, Time=0.62 sec\n",
      " ARIMA(2,1,2)(0,1,2)[12]             : AIC=526.365, Time=5.37 sec\n",
      " ARIMA(2,1,2)(1,1,0)[12]             : AIC=530.219, Time=1.98 sec\n",
      " ARIMA(2,1,2)(1,1,2)[12]             : AIC=inf, Time=9.05 sec\n",
      " ARIMA(1,1,2)(0,1,1)[12]             : AIC=527.568, Time=1.64 sec\n",
      " ARIMA(2,1,1)(0,1,1)[12]             : AIC=529.582, Time=1.52 sec\n",
      " ARIMA(3,1,2)(0,1,1)[12]             : AIC=520.313, Time=1.92 sec\n",
      " ARIMA(3,1,2)(0,1,0)[12]             : AIC=544.911, Time=0.69 sec\n",
      " ARIMA(3,1,2)(1,1,1)[12]             : AIC=521.966, Time=2.93 sec\n",
      " ARIMA(3,1,2)(0,1,2)[12]             : AIC=521.645, Time=5.46 sec\n",
      " ARIMA(3,1,2)(1,1,0)[12]             : AIC=526.036, Time=1.69 sec\n",
      " ARIMA(3,1,2)(1,1,2)[12]             : AIC=523.456, Time=6.39 sec\n",
      " ARIMA(3,1,1)(0,1,1)[12]             : AIC=523.535, Time=0.85 sec\n",
      " ARIMA(4,1,2)(0,1,1)[12]             : AIC=521.961, Time=2.24 sec\n",
      " ARIMA(3,1,3)(0,1,1)[12]             : AIC=522.196, Time=1.73 sec\n",
      " ARIMA(2,1,3)(0,1,1)[12]             : AIC=523.490, Time=1.63 sec\n",
      " ARIMA(4,1,1)(0,1,1)[12]             : AIC=519.977, Time=2.16 sec\n",
      " ARIMA(4,1,1)(0,1,0)[12]             : AIC=550.220, Time=0.62 sec\n",
      " ARIMA(4,1,1)(1,1,1)[12]             : AIC=521.444, Time=2.98 sec\n",
      " ARIMA(4,1,1)(0,1,2)[12]             : AIC=520.895, Time=4.62 sec\n",
      " ARIMA(4,1,1)(1,1,0)[12]             : AIC=526.881, Time=1.23 sec\n",
      " ARIMA(4,1,1)(1,1,2)[12]             : AIC=522.866, Time=8.13 sec\n",
      " ARIMA(4,1,0)(0,1,1)[12]             : AIC=524.721, Time=0.83 sec\n",
      " ARIMA(5,1,1)(0,1,1)[12]             : AIC=521.974, Time=1.83 sec\n",
      " ARIMA(3,1,0)(0,1,1)[12]             : AIC=529.910, Time=0.54 sec\n",
      " ARIMA(5,1,0)(0,1,1)[12]             : AIC=524.411, Time=0.90 sec\n",
      " ARIMA(5,1,2)(0,1,1)[12]             : AIC=523.494, Time=3.99 sec\n",
      " ARIMA(4,1,1)(0,1,1)[12] intercept   : AIC=520.121, Time=4.49 sec\n",
      "\n",
      "Best model:  ARIMA(4,1,1)(0,1,1)[12]          \n",
      "Total fit time: 84.823 seconds\n",
      "                                     SARIMAX Results                                      \n",
      "==========================================================================================\n",
      "Dep. Variable:                                  y   No. Observations:                  204\n",
      "Model:             SARIMAX(4, 1, 1)x(0, 1, 1, 12)   Log Likelihood                -252.988\n",
      "Date:                            Fri, 30 May 2025   AIC                            519.977\n",
      "Time:                                    18:59:58   BIC                            542.743\n",
      "Sample:                                07-01-1991   HQIC                           529.198\n",
      "                                     - 06-01-2008                                         \n",
      "Covariance Type:                              opg                                         \n",
      "==============================================================================\n",
      "                 coef    std err          z      P>|z|      [0.025      0.975]\n",
      "------------------------------------------------------------------------------\n",
      "ar.L1         -0.2112      0.126     -1.683      0.092      -0.457       0.035\n",
      "ar.L2          0.1221      0.120      1.018      0.309      -0.113       0.357\n",
      "ar.L3          0.1174      0.090      1.311      0.190      -0.058       0.293\n",
      "ar.L4         -0.2340      0.077     -3.021      0.003      -0.386      -0.082\n",
      "ma.L1         -0.7149      0.113     -6.315      0.000      -0.937      -0.493\n",
      "ma.S.L12      -0.4786      0.063     -7.613      0.000      -0.602      -0.355\n",
      "sigma2         0.8086      0.053     15.389      0.000       0.706       0.912\n",
      "===================================================================================\n",
      "Ljung-Box (L1) (Q):                   0.03   Jarque-Bera (JB):               176.73\n",
      "Prob(Q):                              0.85   Prob(JB):                         0.00\n",
      "Heteroskedasticity (H):              15.18   Skew:                            -0.36\n",
      "Prob(H) (two-sided):                  0.00   Kurtosis:                         7.66\n",
      "===================================================================================\n",
      "\n",
      "Warnings:\n",
      "[1] Covariance matrix calculated using the outer product of gradients (complex-step).\n",
      "Figure(1200x600)\n",
      " Original data saved as 'original_energy_data.csv'\n",
      " Forecast-only data saved as 'forecast_only.csv'\n",
      " Combined data saved as 'energy_forecast.csv'\n",
      " Plots saved as 'original_energy_consumption.png' and 'energy_forecast_plot.png'\n"
     ]
    }
   ],
   "source": [
    "!python energy_forecast_arima.py"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "bf248ae9",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "DefaultAzureCredential failed to retrieve a token from the included credentials.\n",
      "Attempted credentials:\n",
      "\tEnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.\n",
      "Visit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot this issue.\n",
      "\tManagedIdentityCredential: ManagedIdentityCredential authentication unavailable, no response from the IMDS endpoint.\n",
      "\tSharedTokenCacheCredential: SharedTokenCacheCredential authentication unavailable. No accounts were found in the cache.\n",
      "\tAzureCliCredential: Azure CLI not found on path\n",
      "\tAzurePowerShellCredential: Az.Account module >= 2.2.0 is not installed\n",
      "\tAzureDeveloperCliCredential: Azure Developer CLI could not be found. Please visit https://aka.ms/azure-dev for installation instructions and then,once installed, authenticate to your Azure account using 'azd auth login'.\n",
      "To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/defaultazurecredential/troubleshoot.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\venum\\energy-forecast-arima\\register_environment.py\", line 27, in <module>\n",
      "    ml_client.environments.create_or_update(arima_env)\n",
      "  File \"C:\\Users\\venum\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\azure\\ai\\ml\\_telemetry\\activity.py\", line 288, in wrapper\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\venum\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\azure\\ai\\ml\\operations\\_environment_operations.py\", line 212, in create_or_update\n",
      "    raise ex\n",
      "  File \"C:\\Users\\venum\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\azure\\ai\\ml\\operations\\_environment_operations.py\", line 114, in create_or_update\n",
      "    next_version, latest_version = _get_next_latest_versions_from_container(\n",
      "  File \"C:\\Users\\venum\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\azure\\ai\\ml\\_utils\\_asset_utils.py\", line 825, in _get_next_latest_versions_from_container\n",
      "    else container_operation.get(\n",
      "  File \"C:\\Users\\venum\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\azure\\core\\tracing\\decorator.py\", line 119, in wrapper_use_tracer\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\venum\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\azure\\ai\\ml\\_restclient\\v2023_04_01_preview\\operations\\_environment_containers_operations.py\", line 422, in get\n",
      "    pipeline_response = self._client._pipeline.run(  # pylint: disable=protected-access\n",
      "  File \"C:\\Users\\venum\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\azure\\core\\pipeline\\_base.py\", line 242, in run\n",
      "    return first_node.send(pipeline_request)\n",
      "  File \"C:\\Users\\venum\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\azure\\core\\pipeline\\_base.py\", line 98, in send\n",
      "    response = self.next.send(request)\n",
      "  File \"C:\\Users\\venum\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\azure\\core\\pipeline\\_base.py\", line 98, in send\n",
      "    response = self.next.send(request)\n",
      "  File \"C:\\Users\\venum\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\azure\\core\\pipeline\\_base.py\", line 98, in send\n",
      "    response = self.next.send(request)\n",
      "  [Previous line repeated 2 more times]\n",
      "  File \"C:\\Users\\venum\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\azure\\mgmt\\core\\policies\\_base.py\", line 95, in send\n",
      "    response = self.next.send(request)\n",
      "  File \"C:\\Users\\venum\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\azure\\core\\pipeline\\policies\\_redirect.py\", line 205, in send\n",
      "    response = self.next.send(request)\n",
      "  File \"C:\\Users\\venum\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\azure\\core\\pipeline\\policies\\_retry.py\", line 544, in send\n",
      "    response = self.next.send(request)\n",
      "  File \"C:\\Users\\venum\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\azure\\core\\pipeline\\policies\\_authentication.py\", line 157, in send\n",
      "    self.on_request(request)\n",
      "  File \"C:\\Users\\venum\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\azure\\core\\pipeline\\policies\\_authentication.py\", line 132, in on_request\n",
      "    self._request_token(*self._scopes)\n",
      "  File \"C:\\Users\\venum\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\azure\\core\\pipeline\\policies\\_authentication.py\", line 108, in _request_token\n",
      "    self._token = self._get_token(*scopes, **kwargs)\n",
      "  File \"C:\\Users\\venum\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\azure\\core\\pipeline\\policies\\_authentication.py\", line 98, in _get_token\n",
      "    return cast(SupportsTokenInfo, self._credential).get_token_info(*scopes, options=options)\n",
      "  File \"C:\\Users\\venum\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\azure\\identity\\_credentials\\default.py\", line 277, in get_token_info\n",
      "    token_info = cast(SupportsTokenInfo, super()).get_token_info(*scopes, options=options)\n",
      "  File \"C:\\Users\\venum\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\azure\\identity\\_credentials\\chained.py\", line 219, in get_token_info\n",
      "    raise ClientAuthenticationError(message=message)\n",
      "azure.core.exceptions.ClientAuthenticationError: DefaultAzureCredential failed to retrieve a token from the included credentials.\n",
      "Attempted credentials:\n",
      "\tEnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.\n",
      "Visit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot this issue.\n",
      "\tManagedIdentityCredential: ManagedIdentityCredential authentication unavailable, no response from the IMDS endpoint.\n",
      "\tSharedTokenCacheCredential: SharedTokenCacheCredential authentication unavailable. No accounts were found in the cache.\n",
      "\tAzureCliCredential: Azure CLI not found on path\n",
      "\tAzurePowerShellCredential: Az.Account module >= 2.2.0 is not installed\n",
      "\tAzureDeveloperCliCredential: Azure Developer CLI could not be found. Please visit https://aka.ms/azure-dev for installation instructions and then,once installed, authenticate to your Azure account using 'azd auth login'.\n",
      "To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/defaultazurecredential/troubleshoot.\n"
     ]
    }
   ],
   "source": [
    "!python register_environment.py"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3434ebb5",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
